name: cool_ui
description: "A state-driven, animation-first, rounded Flutter UI framework that derives an entire visual language from two colors supplied by the user."
version: 1.0.0
homepage: https://github.com/mister-ritom/cool_ui
repository: https://github.com/mister-ritom/cool_ui
issue_tracker: https://github.com/mister-ritom/cool_ui/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
